### ISSUE TITLE
make prod version=4.0 php=8.1

### ISSUE THREAD

**Issue by rafalohaki** [chevereto/v4-docker#41]
is it possible to use own remote mysql server instead of dockered one?
btw i get error with command make prod version=4.0 php=8.1
[* unhealthy] Waiting for chevereto4.0-prod-php8.1... is spamming 
logs are in loop spam too
```
* Extracting package

* Installing dependencies

Composer could not find a composer.json file in /var/www/html

To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage

/var/CONTAINER_STARTED_PLACEHOLDER

Making working dir /chevereto/download

cd /chevereto/download

* Downloading chevereto/v4 4.0-lite package

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed
```

**Comment by rodber** [comment]
> is it possible to use own remote mysql server instead of dockered one?

Of course, you need to provide the database variables and customize your docker compose file.

> btw i get error with command make prod version=4.0 php=8.1

As you may notice this repo isn't versioned, it is still on development preview. I'm working on #37 at this time which changes provisioning so it will be better to don't use it for a while.

By the way, this repo for **development standard**. It is not intended for production usage.

**Comment by rodber** [comment]
Hey @rafalohaki 

The new provisioning (PHP-FPM) has been published. You can now simply run:

```sh
make prod
```

## Regarding production

This repo provide a production-like instance. The difference vs [container-builder](https://github.com/chevereto/container-builder) is that in this project the software is provided in a persistent layer after the installation step. I've improved this repo by providing the dependencies at the [image layer](https://github.com/chevereto/docker/blob/4.0/chevereto/4.0/Dockerfile#L101) so the deps that you end using are the same. It also carries a `dump-autoload` so the dependencies don't need any resolving (fast as it gets).

You should consider using this production provisioning when you intend to customize the application source code, this is because you are in charge of carrying the application filesystem updates as there's no `update.sh` at the moment (there's an [open issue](https://github.com/chevereto/docker/issues/42))

## container-builder

The production standard will be updated shortly to match the provisioning here. It may take me a couple of days.
